### ISSUE TITLE
Does not remove fbclid query parameter.

### ISSUE THREAD

**Issue by Zekt** [mgziminsky/FacebookTrackingRemoval#20]
Facebook added a new tracking parameter “fbclid” on links posted on Facebook, though requests to pixel server is blocked I think it’s still best to remove it.

**Comment by mgziminsky** [comment]
Thanks for reporting. 

This new parameter is being added to 3rd party links, which are currently left alone, so I'll need to think a bit about how I want to deal with it. 

Also, since the pixel server blocking only applies to FB itself, it unfortunately won't help in this case, since the request would be happening on the 3rd party site.

In any case, I'll try to get have something out addressing it this week.
