### ISSUE TITLE
Facebook™ Tracking & Ad Removal

### ISSUE THREAD

**Issue by dave3114** [mgziminsky/FacebookTrackingRemoval#22]
**Describe the bug**
The Add-On doesn't seem to affect FB sponsored ads. Ads appear every 5-6 posts. Tried deleting and re-adding the Add-On.  FB ads appear the same if your Add-On is removed.

**To Reproduce**

**Expected behavior**
Per your email to me, all FB ads (sponsored or not) should not appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/45341832/48985619-98a5e580-f0c6-11e8-800f-cf1590aea371.png)

**Please provide the following information:**
 Dell All-In-One 3048
 Win 8.1
Firefox V 63.0.3
 - Extension Version 1.6.1
 - Extension Options - default

**Additional context**

**Comment by mgziminsky** [comment]
Thanks for reporting. From your screenshot, I can see the extension is at least partially working since the sidebar ads are collapsed, so the tracking prevention's should still work at least. 

A couple questions to get a bit more info:
- Have you tried enabling the pending hide rules under the advanced options section? 
- Is it only sponsored posts that are showing? or are you seeing suggestions as well? (eg: Suggested Post, Suggested Friends, etc.)

Unfortunately, there is not much I can do about this on my own, since things are working correctly on my FB, and that's all I have to work with. It's most likely that FB is giving you a different version of the site code than what they are giving to me. 

If you want, take a look at my comment [here](https://github.com/mgziminsky/FacebookTrackingRemoval/issues/19#issuecomment-419748602) and follow the "Finding The Selector" instructions. The ability to test is now built into the extension, so once you find the selector described in step 4, you can paste it into the "Custom CSS selectors..." text area in the advanced options and see if it works. If you do find one that works, let me know what it is and I'll add it to the extension so everyone else benefits.

**Comment by mgziminsky** [comment]
@dave3114 

I found someone I know that was also seeing ads find a selector that fixed it for them.

Would you try adding `a.e_8yb3o_hsi` to the "Custom CSS selectors..." field in the advanced options and seeing if that works for you as well. If it does, I'll add it to the pending list for a while and then the main list.

**Comment by mgziminsky** [comment]
Since I haven't heard back from you, I added that selector to the pending list. I'm going to wait a few more days to hear back from you on if it worked and then close.

**Comment by dave3114** [comment]
Michael,

Just took a careful look at my FB. Scrolled through over 100 posts.
ALL Sponsored posts have now disappeared. 
No ads on the side.
I didn’t make any changes other than adding your Add-On.
Hope that it continues.
Many thanks.

Dave
