### ISSUE TITLE
My posts are not shown in groups

### ISSUE THREAD

**Issue by VTX6** [mgziminsky/FacebookTrackingRemoval#23]
Hello!

**Describe the bug**
The extension is nearly perfect. But for me (at least) my own group posts are not shown. When I turn off the extension, it's there though. 

**To Reproduce**
1. Go to a private group (did not try it in public groups)
2. My posts are not shown
3. Turn off the extension, then it refreshes the page
4. My posts are there

**Expected behavior**
I should see my own posts in the group when the extension is turned on.

**Screenshots**
With the extension off: https://pasteboard.co/HSqZsNr.png
With the extension on: https://pasteboard.co/HSqZHXN.png

Hope you can fix it.
Thank you!

**Comment by mgziminsky** [comment]
Thanks for reporting, but please fill out a complete request using the Bug Report template. 
Once you've updated, I'll be able to look into it further.

**Comment by VTX6** [comment]
> Thanks for reporting, but please fill out a complete request using the Bug Report template.
> Once you've updated, I'll be able to look into it further.

Updated.

**Comment by VTX6** [comment]
> Thanks.
> 
> I can't seem to reproduce though. What are the options you have set for the extension? Are you using the defaults?

These are my options: https://pasteboard.co/HStFTZi.png

I'm using some other extensions that my interfere with yours:
- uBlock Origin
- QCLean:Remove Facebook Ad,Suggested Page&Post
- Pop up blocker for Chrome™ - Poper Blocker

**Comment by mgziminsky** [comment]
Ok, to help me narrow it down, would you mind doing a few more things for me:
- Set the hide method back to collapse and see what it is says in the collapsed summary.
- Individually enable/disable the sponsored and suggestions options and let me know which of them causes the issue.

It's unlikely other addons would interfere with mine due to how it's implemented, but not impossible. uBlock should be fine, I use it as well. I'm not familiar with QClean, so maybe try disabling that one while mine is enabled and seeing if that makes a difference.

**Comment by VTX6** [comment]
Thank you!

It was the "Hide inline suggestions" option that made my posts disappear. When I turn it off and the page refreshes, my post is there.
