### ISSUE TITLE
Sponsored Ads only show

### ISSUE THREAD

**Issue by blwanta** [mgziminsky/FacebookTrackingRemoval#24]
# Requests about ads not being hidden will be closed without response. Follow the instructions in the "Ad blocking support" template for that.

**Describe the bug**
Only "Sponsored" ads are showing

**Please provide the following information:**
 - Device: [Desktop]
 - OS: [Windows]
 - Browser [firefox]
 - Extension Version [1.6.2]
 - Extension Options [Enabled, 1, 4, 5. Collapse. Advanced: Enable Pending...., checked]

**Additional context**

**Comment by mgziminsky** [comment]
Can you provide screenshots? 
Are you saying that normal posts are being hidden and sponsored are being shown?
Is it possible that a different addon is interfering with mine?

I'm sorry, but as with your previous issues, there isn't really anything I can do without being able to reproduce what you are seeing, or getting significantly more technical details in order to diagnose.

**Comment by mgziminsky** [comment]
Closing. Fairly confident this is not due to my addon.
