### ISSUE TITLE
Prevents gallery images in Messenger from loading

### ISSUE THREAD

**Issue by bcyphers** [mgziminsky/FacebookTrackingRemoval#26]
See bug report here: https://github.com/EFForg/privacybadger/issues/2214, with instructions to reproduce.

**Comment by mgziminsky** [comment]
Thanks for letting me know about this. I actually ended up finding several other issues with various elements of the messenger page caused by one of the other options of my addon while looking into this. I don't believe any of the other issues I found affect you, but I'll let you know if I come across any that do.

**Comment by mgziminsky** [comment]
@bcyphers 

While testing, I noticed that FB was resetting the links on file attachments on the messenger page. You may not care for Privacy Badger, since these are still technically internal links, but I'm not sure if it is happening in other places as well. I'm handling this by now observing href attribute changes, but this does add a small amount of overhead to link cleaning since any cleaned links will be processed at least twice.

See 25340f431f4c6d3567717918c08346d8dfe8ad36 for the details.

**Comment by ghostwords** [comment]
The `aria-label` attribute for photos is apparently localized (!): https://github.com/EFForg/privacybadger/issues/2214#issuecomment-549481391
