### ISSUE TITLE
Make it work for Messenger.com (domain)?

### ISSUE THREAD

**Issue by michalrus** [mgziminsky/FacebookTrackingRemoval#27]
**Is your feature request related to a problem? Please describe.**
Well, not a problem, but it seems to work only on facebook.com — messenger.com doesn’t get link tracking removed etc.

**Describe the solution you'd like**
Have it working on messenger.com?

**Describe alternatives you've considered**
N-n-none…

**Additional context**
—

**Comment by mgziminsky** [comment]
Thanks for the suggestion. 

From what I can tell, that's just a landing page for the messenger app right? I only see 4 links on that page, and nothing interactive. 2 of the links are already plain, 1 only contains a internal metric param, and the other appears to be a benign internal redirect. If the 1 redirect is what you're worried about, it would be simpler to just not click it and navigate to the target site manually (https://messenger.fb.com).

So unless I'm missing something, I don't see any benefit to running on messenger.com, since there isn't really any tracking going on.

**Comment by michalrus** [comment]
@mgziminsky, oh, maybe you have some blocker (uMatrix?), that’s removing the login form for you?

If so, add these:
```
messenger.com facebook.com cookie allow
messenger.com facebook.com xhr allow
messenger.com facebook.net script allow
messenger.com fbcdn.net media allow
messenger.com fbcdn.net script allow
messenger.com fbcdn.net xhr allow
```

So without any blocker, you can log in on Messenger.com using your regular Facebook credentials, and have access to messaging via that web app. There, you can click links from messages etc.

**Comment by michalrus** [comment]
(The benefit being that, despite them looking ± the same, `messenger.com` is faster and more responsive than `facebook.com/messages`.)

**Comment by mgziminsky** [comment]
Ah, I see now. I use uBlock Origin, but I thought I had turned it off when I checked the page the first time, guess I didn't. That being the case, I'll add it.

You wouldn't happen to know if they have a tor .onion address for messenger as well would you?

**Comment by michalrus** [comment]
I don’t know, never heard of one… =( I only know that Facebook one.

Thank you for considering this! =)

**Comment by michalrus** [comment]
Thank you!
