### ISSUE TITLE
extension randomly stopped at fennec

### ISSUE THREAD

**Issue by karasawa-user** [mgziminsky/FacebookTrackingRemoval#35]
Decide to roll back to 1.7.1 because the latest version randomly stop working which indicated by disappearance of extension icon. Currently can't intentionally produce the error so I can't fill bug reproduction step.

 - Device: Lenovo A6600 plus
 - OS: android 6.0
 - Browser fennec 67.0.1
 - Extension Version 1.8.0.2
 - Extension Options: remove tracking from external & internal link + hide inline suggestion in collapse mode

**Comment by mgziminsky** [comment]
Was it working at first then stopped working? Or does it never work on the new version?
How did you install the update? Manually from here or the addon page, or did it install automatically?
Did you refresh your facebook tab after updating?
Have you tried to do a clean install of the newest version? Uninstall first then re-install

I am unable to reproduce, so your answers to the above questions might provide some insight. You also seem to be using quite an old version of fennec, so updating that may help as well.

**Comment by karasawa-user** [comment]
It's completely random so I can't reproduce it too, sometimes it just stopped midway or won't load at all at start though it eventually work again. Fresh install only work for few hours before it randomly disappear again and as for my fennec version currently can't update it for time being because my phone being picky about update so it's probably caused by that

**Comment by mgziminsky** [comment]
Hmmm, strange, and this only happens on the new v1.8.0.2 version? I don't use my phone for facebook, I only really posted this with support because there wasn't any reason not to, so it's easy for me to overlook things that may cause issues there, sorry.
When you say it doesn't load, or stops midway, does it always manifest with the disappearance of the icon from the address bar? or does it sometimes just stop fixing things with the icon still there?

Without a reliable way to reproduce, my best guess would be that it's related to my change to load the extension at the beginning of the page load instead of the end. Previously, the extension didn't load in until everything on the page was ready, now it injects right away and waits for the page to reach the state it can work with. In that case though, the icon should still always be there since that should be controlled by the browser and not be based on if the injection is successful.

I'll try to find a way to investigate more when I get some time. If you notice anything else that may help in reproducing or narrowing it down let me know. For now though, if the old version still works you can keep using it without issue since the only new additions were related to performance.

**Comment by karasawa-user** [comment]
Sorry for missing... Testing the extension again and so far the icon is the only indicator whether it still work or not and I can guarantee it never stopped working without leaving the icon off
