### ISSUE TITLE
New Version of Facebook Removes Expected HTML Attributes this Tool Expects

### ISSUE THREAD

**Issue by ablanathtanalba** [mgziminsky/FacebookTrackingRemoval#36]
**Describe the bug**
Facebook rolled out a new version of their web app this month, which changed almost all of the DOM structure that it used to have, including the HTML attributes that this project looks for in its link cleaning functionality. It seems like all of that readable data is now obfuscated through complicated `class` attributes with seemingly random string values.

**To Reproduce**
1. Go to 'Facebook.com'
2. If you're not automatically updated to the new version of Facebook, click on the dropdown menu from the top right arrow, choose the new UI option.
3. Inspect any link in the dev tools, see that the structure is very different.
 
**Expected behavior**
link cleaning can no longer take place as expected

**Screenshots**
Here is an example screenshot of the new structure, the highlighted portion is the anchor tag on a random post in a Facebook feed:
![Screen Shot 2020-05-19 at 11 04 27 AM](https://user-images.githubusercontent.com/25778052/82362064-9ae9b700-99c0-11ea-811b-560bcd31efdf.png)

**Please provide the following information:**
 - Device: MacBook Pro
 - OS: macOS Catalina
 - Browser Both Firefox and Chrome
 - Extension Version [e.g. 1.6.1]
 - Extension Options

**Additional context**
Some of this functionality is also used in [Privacy Badger](https://github.com/EFForg/privacybadger), we will be keeping an eye on this space. Thank you!

**Comment by mgziminsky** [comment]
Thanks for the details. I still don't have the option to switch to the new design, so there's not much I can do until I can use it. If it doesn't show up for me soon, I may make a throwaway account and try with that if I don't get the option soon though.

**Comment by Krashlog** [comment]
Just FYI, it doesn't work with the old version either. I'm still on the old one and have been seeing ads for a few weeks now. But I guess we'll all switch to the new version eventually, so it might be better to concentrate your efforts on fixing the new one.

**Comment by mgziminsky** [comment]
So this extension should still work without modification on both versions in regards to fixing redirect links, which is what your screenshot and linked issue are referring to. I took a peek at the privacy badger issue, and you are using an additional attribute filter there that I don't use. It was added in https://github.com/EFForg/privacybadger/commit/40d46b6cb78d252e058cc8015afbf7157302eaf7 to fix some sort issue with messenger images. I vaguely remember when that change was made, but can't remember if there was a reason I didn't do the same or not.

As far as I can tell, at least as of now, that filter isn't necessary for my extension. I don't see any issues with images on messenger.com or in the embedded messenger on FB. If you have any more details or insight that could be useful, let me know, otherwise I think I'm going to close this issue since there are already a couple others open relating to the new design and ads being shown.

**Comment by ablanathtanalba** [comment]
Thanks for the feedback @mgziminsky . Forgive me for not having a great understanding of this codebase -- will the [cleanAttrs(elem)](https://github.com/mgziminsky/FacebookTrackingRemoval/blob/114c04d5582dfc0e49b3789334956db85fd6c82b/src/util.js#L75) throw a wrench into the functionality of this tool if all the previous anchor attributes have been obfuscated and collapsed into the `class` one?

**Comment by mgziminsky** [comment]
Ok, I think I understand what you were trying to say now. Is this an issue you are actually experiencing? or was it just an assumption? What are the specific attributes you are referring to when you say "this tool expects?" If you opened this because you assumed it had the same issue fixing redirects as what you are referring to in https://github.com/EFForg/privacybadger/pull/2607, then that at least is not the case as I explained in my previous comment.

I don't actually use or reference any data in attrs as part of this extension. At most, they may be used to narrow the scope of certain selectors used primarily for ad removal. `cleanAttrs` has no expectations or dependency on specific attributes being present, I added it purely as a proactive measure against potential tracking.

Now, with that said, regarding the claim that the new classes are actually obfuscated data, do you have any proof of that? If that is truly what is happening, then I will probably want to do some pruning of the classes as well, assuming they can be distinguished in some way. In that case though, i'll create a new issue.

**Comment by mgziminsky** [comment]
Closing since as far as I can tell, this isn't an issue for this extension.
