### ISSUE TITLE
When enabled, facebook says 'you appear to be offline', and certain parts of the UI don't appear

### ISSUE THREAD

**Issue by deusexcalamus** [mgziminsky/FacebookTrackingRemoval#48]
**Describe the bug**
As the subject says, when I go to facebook with this extension enabled, a popup in the lower left will say something to the effect of 'you are offline', and if I try to like/haha/etc a post, everything but the 'like' button on the hover over doesn't show up.

**To Reproduce**
go to facebook
try to react to a post with anything but 'like'
error.
**Expected behavior**
Should be able to use other reacts, should also not show the aforementioned message about being offline.

**Screenshots**

**Please provide the following information:**
 - Device: [e.g. Desktop, iPhone6, etc.]
 Windows Desktop
 - OS: [e.g. Windows, Linux, iOS]
 Win10 x64 pro
 - Browser [e.g. firefox, chrome]
 Firefox latest stable
 - Extension Version [e.g. 1.6.1]
 Latest version
 - Extension Options
Everything enabled except for:
Remove tracking values...
Inline videos on mobile...
Add styling to modified elements.
**Additional context**
![image](https://user-images.githubusercontent.com/8674645/118347269-75c25280-b507-11eb-8e01-ca295d6c2b3f.png)

**Comment by Pezor** [comment]
I'm having the same issue.

**Comment by jbionic2016** [comment]
The same issue here too.
I don't think the pop-up is necessary, so could you please add the option to hide it?

**Comment by deusexcalamus** [comment]
> 
> 
> The same issue here too.
> I don't think the pop-up is necessary, so could you please add the option to hide it?

Whether its necessary or not isn't the issue, I opened the ticket because the extension is (likely) causing the message to appear from facebook.

**Comment by jbionic2016** [comment]
> > The same issue here too.
> > I don't think the pop-up is necessary, so could you please add the option to hide it?
> 
> Whether its necessary or not isn't the issue, I opened the ticket because the extension is (likely) causing the message to appear from facebook.

I didn't even know if this pop-up was due to Facebook. All I know that when the  FacebookTrackingRemoval extension is off, then  the pop-up doesn't show up

**Comment by deusexcalamus** [comment]
The popup comes from facebook, as far as I can tell, and the extension is the cause of it.

**Comment by jbionic2016** [comment]
> The popup comes from facebook, as far as I can tell, and the extension is the cause of it.

You may be right. I've just right-clicked on the pop-up and blocked it with Adguard Adblocker option available from the context menu, so the pop-up doesn't show up again. Perhaps you can try to use your adblocker too.

**Comment by deusexcalamus** [comment]
> 
> 
> > The popup comes from facebook, as far as I can tell, and the extension is the cause of it.
> 
> You may be right. I've just right-clicked on the pop-up and blocked it with Adguard Adblocker option available from the context menu, so the pop-up doesn't show up again. Perhaps you can try to use your adblocker too.

I would rather address the root cause than a symptom.

**Comment by mgziminsky** [comment]
This is 2 separate issues, but i'm looking into it.

For the network warning, it can be ignored since I am blocking the background beacon and ping requests that facebook sends constantly, about every 5 seconds. As far as I can tell, the warning is just a false alarm from FB, and everything still works fine. I can probably allow the network ping, since it doesn't seem to contain any actual information, but FB is almost certainly using that ping to track how long people are actively on the site. I'll consider making a dedicated option for controlling the background request blocking.

The reaction issue is likely a separate problem and I'll look into fixing it soon.

**Comment by deusexcalamus** [comment]
@mgziminsky Would you have any idea why the network issue cropped up now all of a sudden? One would think that if you were blocking it all along, it would have presented itself previously.

**Comment by mgziminsky** [comment]
It was just a change on FBs end. They just didn't have a notification before and now they do, or the trigger for it used to be different. As mentioned by jbionic, you can hide it using a separate extension such as ublock Origin if you want to.

Unless I determine that it is causing actual problems with functionality, I'm not all that inclined to address it other than maybe adding a built-in option to hide it or something.

**Comment by deusexcalamus** [comment]
No worries, I was just curious. More interested in the fix for the reaction issue, at any rate. Thanks for developing this extension :)

**Comment by mgziminsky** [comment]
So it turns out that once the heartbeat ping fails, FB will just stop doing certain things, such as loading the reaction emojis, or uploading files as described by #49...

If you hover over a like button or attempt an upload before the "offline" warning appears, they work fine, but once that notification shows up they will just stop working... I am going to attempt to bypass the error first, but if i'm unsuccessful I will likely just stop blocking the heartbeat.

I should hopefully have an update out within the next few days. If you have a bit of time to do a quick spot check of all the features you're used to using and let me know if you notice any other issues, it would be a huge help to make sure i'm not missing anything.
