### ISSUE TITLE
Marketplace ads not hidden

### ISSUE THREAD

**Issue by fpusersuggest** [mgziminsky/FacebookTrackingRemoval#51]
# Requests about ads not being hidden will be closed without response. Follow the instructions in the "Ad blocking support" template for that.

**Describe the bug**

The extension doesn't work. I have installed that but does not filter anything.

**To Reproduce**
1. Go to '...' facebook
2. Click on '....' browse marketplace 
3. Scroll down to '....' scrool download and found 6 ads out of 8.
4. See error none

**Expected behavior**
working

**Screenshots**

https://ibb.co/ss1WQpK

**Please provide the following information:**
 - Device: [e.g. Desktop, iPhone6, etc.] laptop
 - OS: [e.g. Windows, Linux, iOS] Ubuntu 20.04 LTS 64bit
 - Browser [e.g. firefox, chrome]  Firefox 94.0 64bit
 - Extension Version [e.g. 1.6.1]  1.9.3
 - Extension Options default

**Additional context**
nothing more

**Comment by mgziminsky** [comment]
Marketplace ads apparently work differently from the news feed, so that isn't currently supported, mainly because I don't use the marketplace and haven't ever really looked into it. I may take a look if when I find the time.

Does it work correctly on the news feed? If not, that could be due to your language setting. I haven't added support for most other languages so far, but if you let me know which language you use, i could at least add that quickly.

**Comment by fpusersuggest** [comment]
Hello,
no, it doesn't work even in news feed.
I tried with what's written in the teamplate tutorial, but it does not hide anything.
