### ISSUE TITLE
Very high CPU usage to the point of freezing Chrome

### ISSUE THREAD

**Issue by LosD** [mgziminsky/FacebookTrackingRemoval#53]
**Describe the bug**
I'm seeing very high CPU usage from Facebook with the extension active, especially after clicking images. As it opens, all browser windows freezes for 4-5 seconds. If I disable the extension, it stops (okay, CPU usage is still rather high, it _is_ Facebook after all, but not surprisingly high). It seems to do the same as you close the image.

**To Reproduce**
1. Open Chrome's Task Manager, sorted by CPU usage.
2. Open Facebook, watch it shoot to 100+% CPU usage.
2. Click on an image.
3. Freezing

**Expected behavior**
"Normal" CPU usage, no freezing.

**Screenshots**

**Please provide the following information:**
 - Device: Desktop computer. A bit old (6th generation i7 6700K), but fast for its age. 64 GB RAM.
 - OS: Windows 10
 - Browser: Chrome
 - Extension Version: 1.9.3
 - Extension Options:
![image](https://user-images.githubusercontent.com/1282832/160342335-1afb43b0-b2c4-4559-94d8-699a8dcc9931.png)

**Additional context**
I think it started a month or so ago. Not sure if it was ~an extension or~ a Chrome update or Facebook change that started it

Edit: Just checked version history. Definitely not an extension update

**Comment by mgziminsky** [comment]
Sorry, I can't seem to reproduce. Do you have any other extensions installed that could be conflicting with this one?

If you wanted to try investigating a bit more thoroughly on your end, you can run the profiler built into the developer tools (Performance tab) and look at the bottom up view to see if anything stands out. Here is the result of a 30 sec capture on my end including clicking images and heavy scrolling to load in content:

![image](https://user-images.githubusercontent.com/1260554/160452582-a4269e6e-7e7d-4eef-8d38-9d85dd0d2ab5.png)

**Comment by LosD** [comment]
Well I DO have a gazillion extensions installed, so can't quite say that there isn't.

Took a trace, and the culprit seems to be a pointerover event handler:
![image](https://user-images.githubusercontent.com/1282832/161052075-23231b1a-3c3c-48ef-91c7-7800bbe5091a.png)

**Comment by LosD** [comment]
It seems to disappear if I disable "Remove tracking from external links".

**Comment by mgziminsky** [comment]
Sounds to me like it is most likely a conflict with another extension. My best guess is that you have another extension that is also monitoring and modifying the `href` of links, so this extension and the other one are causing an infinite loop between each other. If you change the profiling view to "Group by Domain" it may show you the source of the `pointerevent` calls, since I don't use that event in this extension.

As a final check that it is a conflict, would you be able try running chrome with only this extension enabled and see if it is still broken? If it is still broken by itself, then I'll look into it more. But if it works, then there isn't much I can do.

**Comment by LosD** [comment]
That's fair. I disabled other extensions, but unfortunately it didn't really help.

Here's the new profile without extensions:
![image](https://user-images.githubusercontent.com/1282832/161124716-170cc81c-d24f-4d94-93e4-3e855f64c611.png)

Here it is grouped by domain. I opened the extension so you can see what is most active:
![image](https://user-images.githubusercontent.com/1282832/161124976-c8f1f016-9a91-4abf-9360-b041359bfd7a.png)

It looks like it is Facebook being triggered to do, errrr ... something... I checked inside "unattributed", and it all seems to be scripts from fbcdn.

**Comment by mgziminsky** [comment]
Sorry, I'm not sure there's anything I can do.. I didn't look at your profiler times initially, but looking now, even your original run looks totally normal. Depending how long the capture was, those Self/Total times are actually completely normal, so whatever is going on isn't getting picked up by the profiler.

As a way of tracking link interaction, FB updates certain links when it detects the mouse on the link, and that is my best guess as to what is causing the `pointerover` event. If FB is changing the link, then the extension is changing it back, and then FB again, and so on... that could be causing the lockups you are seeing. I try to fix such links and disable the FB script ahead of time, but if that's not working for some reason, I could imagine this sort of issue.

All of that is just an educated guess though. Since I'm unable to reproduce the issue on my end, there is no easy way for me to investigate more thoroughly :/

**Comment by LosD** [comment]
The run is only from opening an image and closing them again. So maybe 6-7 seconds including the browser being frozen. Scripts running for half that time hardly seems normal to me?

Oh well, if you can't reproduce, you can't reproduce, that's how it is sometimes. Do you want me to leave it open, or should I just close it?
