### ISSUE TITLE
Remove new Messenger popup

### ISSUE THREAD

**Issue by NguyenASang** [mgziminsky/FacebookTrackingRemoval#59]
**Describe the feature request**
Add an option to remove "new Messenger" popup appears in [Facebook Messenger](https://www.facebook.com/messages).

**To Reproduce**
1. Go to https://www.facebook.com/messages
2. A popup will appear

**Screenshot** 

![download (1)](https://user-images.githubusercontent.com/87893636/183000059-7dbf6eaa-339f-412a-8f0d-64ec1c30dc4e.png)

**Additional context**
The new version has removed "Sponsored posts" in Facebook Watch and the "Custom CSS"  has been fixed, thank you very much.

**Comment by mgziminsky** [comment]
Sorry, once again, I'm not going to add a one off option just for this. I also think hiding this type of modal dialog is out of the scope of this extension.

To achieve this, you would be better off using the "element picker" feature of the uBlock Origin extension. You can also try to identify the appropriate rule for this extension yourself and add it as another custom rule, but I don't think I'm going to add it here.

**Comment by NguyenASang** [comment]
Hi, thanks for the reply, but I really can't find the rule to remove that, I try many times with Ad Guard extension but no hope. Can you create a rule to remove that popup, thanks in advance.

**Comment by mgziminsky** [comment]
This extension is not compatible with AdGuard rules, you need to add it to AdGuard. This extension works very differently from other ad blockers, it's specifically for FB in order to work around their anti-adblocking tricks.

I'm not familiar with AdGuard, but highly recommend uBlock Origin, which has a built-in tool for doing exactly this sort of thing: https://github.com/gorhill/uBlock/wiki/Element-picker

**Comment by NguyenASang** [comment]
Well, thank you for your suggestion, I'm still considering between uBlock Origin and AdGuard. But I think I will choose uBlock Origin :D
