### ISSUE TITLE
Extension suddenly doesn't work

### ISSUE THREAD

**Issue by geloboyao** [mgziminsky/FacebookTrackingRemoval#66]
**Describe the bug**
The first time I used the extension, I am tweaking the settings. One day, it doesn't work anymore. I tried to restore default settings but still doesn't work. I tried to reinstall the extension and it works again. This time, I didn't tweak anything from the extension. Somehow, it doesn't work again. Tried to restore default settings but doesn't work again.

**To Reproduce**
1. Wait for 2 days. (Reinstall date is November 29, bug found on December 1)

**Expected behavior**
Ads and suggested posts should be inline.

**Screenshots**
![bug](https://user-images.githubusercontent.com/17458597/205036852-a20b2610-f8a9-47f5-b29e-aab30740ed91.png)

**Please provide the following information:**
 - Device: Desktop
 - OS: Windows 10
 - Browser: Firefox
 - Extension Version: 1.10.4
 - Extension Options: *see attached screenshot*

**Additional context**
None

**Comment by mgziminsky** [comment]
I'm not seeing issues on my end, but there are a couple things that could cause this:
1. Facebook is in the process of changing things and it just hasn't been rolled out to me yet. I will fix it when it eventually does.
1. The extension is failing to load the updated blocking rules. This could happen if your internet connection isn't reliable or you are somehow blocking requests to mgziminsky.gitlab.io
   - I'm aware of this bug, but just haven't got around to fixing it yet.

If it works sometimes, then suddenly doesn't, it's most likely number 2. To fix in that case, make sure you have internet then click the "Refresh Rules" button under the advanced options. That should load the updated blocking rules and refresh the page. If that still doesn't work, then I'll need you to get some more information for me in order to investigate.
