### ISSUE TITLE
what is this It's on the left side of the page. Is it a bug?

### ISSUE THREAD

**Issue by Kuju29** [mgziminsky/FacebookTrackingRemoval#76]
what is this It's on the left side of the page. Is it a bug?
```
<div class="__fb-dark-mode FBTR-PROCESSED"><svg style="overflow: visible;"><text id="gid525" y="13" style="fill: currentcolor; font-size: 12px; overflow: visible;">Learn More</text></svg><div><div class="FBTR-PROCESSED"></div></div></div>
```

![image](https://github.com/mgziminsky/FacebookTrackingRemoval/assets/22098092/f4c26603-434c-400e-99cf-106c189e42f1)

If you scroll too much, it will come up. and it makes it impossible to press the home page
![image](https://github.com/mgziminsky/FacebookTrackingRemoval/assets/22098092/c16cbd40-ab06-4a1a-bde8-4677334670ce)

**Comment by mgziminsky** [comment]
It's a FB bug. It will happen even without any extensions after scrolling for a certain amount of time due to how they are trying to obscure their post labels. It has been present since around September 2022.

# Technical Details

Their method is actually pretty clever, but their implementation is dumb. What they are doing is abusing the [svg use](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use) feature to hide their label text out of line. This makes it impossible create purely pattern based ad hiding rules like those used in general adblocking extensions. It can be easily handled by some [very simple javascript](https://github.com/mgziminsky/FacebookTrackingRemoval/commit/91e027029af1a0e7595951f59d70fa1437204192#diff-9c0ec1b0a889e599f3ff81590864dd9dc65684a86b41f1da75acc53fafed12e3R251) though.


The way they hide these labels on the page though was completely thoughtless. Instead of moving the container completely off the page from one of the sides or below the bottom, they decided to just move it up by a fixed pixel amount above the top of the screen. So after scrolling for a while, the element grows larger than that offest and starts interfering with the page.

![image](https://github.com/mgziminsky/FacebookTrackingRemoval/assets/1260554/2e9d1aba-ca87-4212-8a73-fe13187f55db)

So out of their 4 choices on where to move it, they literally picked the only one that was wrong 🤦‍♂️
